### ISSUE TITLE
TypeError: GaussianRasterizationSettings.__new__() got an unexpected keyword argument 'kernel_size'

### ISSUE THREAD

**Issue by next1foreal** [if-ai/ComfyUI-IF_Trellis#13]
TypeError: GaussianRasterizationSettings.__new__() got an unexpected keyword argument 'kernel_size'

**Comment by LionBuer** [comment]
same

**Comment by if-ai** [comment]
I fixed this on the latest I was testing to use a simpler gaussian lib but it sucks so back to normal

**Comment by t-ley** [comment]
I'm still getting this error:


# ComfyUI Error Report
## Error Details
- **Node ID:** 84
- **Node Type:** IF_TrellisImageTo3D
- **Exception Type:** TypeError
- **Exception Message:** GaussianRasterizationSettings.__new__() got an unexpected keyword argument 'kernel_size'
## Stack Trace
```
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_Trellis.py", line 323, in image_to_3d
    video_path, glb_path, _, _, _, _ = self.generate_outputs(
                                       ^^^^^^^^^^^^^^^^^^^^^^

  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\IF_Trellis.py", line 189, in generate_outputs
    video_gs = render_utils.render_video(gaussian_output)['color']
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\utils\render_utils.py", line 96, in render_video
    return render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': bg_color}, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\utils\render_utils.py", line 73, in render_frames
    res = renderer.render(sample, extr, intr, colors_overwrite=colors_overwrite)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\renderers\gaussian_render.py", line 223, in render
    render_ret = render(camera_dict, gausssian, self.pipe, self.bg_color, override_color=colors_overwrite, scaling_modifier=self.pipe.scale_modifier)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_Trellis\trellis\renderers\gaussian_render.py", line 73, in render
    raster_settings = GaussianRasterizationSettings(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.3.2
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170956288
  - **VRAM Free:** 14204431904
  - **Torch VRAM Total:** 1711276032
  - **Torch VRAM Free:** 196505120
